export const UI = {
  UI_DATA: 'UI_DATA',
  ADD_TAB: 'ADD_TAB',
  REMOVE_TAB: 'REMOVE_TAB',
  SET_ACTIVE_TAB: 'SET_ACTIVE_TAB',
  UPDATE_FILTER: 'UPDATE_FILTER',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  SET_LOADING: 'SET_LOADING',
  UPDATE_LABEL: 'UPDATE_LABEL',
  DISPLAY_MODAL: 'DISPLAY_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL'
}

export const SF_TASK_DATA = 'SF_TASK_DATA'
export const SEARCH_TYPE = {
  IMAGES: 'images',
  VIDEOS: 'videos'
}

export const SEARCH = {
  SEARCH_DATA: 'SEARCH_DATA',
  SAVE_SEARCH_DATA: 'SAVE_SEARCH_DATA',
  UPDATE_SEARCH_DATA: 'UPDATE_SEARCH_DATA',
  CLEAR_SEARCH_RESULTS_DATA: 'CLEAR_SEARCH_RESULTS_DATA',
  ATTACH_UUID_TO_SEARCH_CONTAINER: 'ATTACH_UUID_TO_SEARCH_CONTAINER'
}